---
- name: Install apache2
  hosts: apache
  remote_user: root
  become: true
  become_user: root

  tasks:
    - name: Install package
      ansible.builtin.apt:
        update_cache: true
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - mysql-server

    - name: Gather the rpm package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Install ufw
      ansible.builtin.apt:
        update_cache: true
        name: ufw
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: start apache2
      ansible.builtin.service:
        name: apache2
        state: started
      when: "'apache2' in ansible_facts.packages"

    - name: Copy index.html if apache2 is installed
      ansible.builtin.template:
        src: ../files/day.j2
        dest: /etc/jour
        mode: '0644'

    - name: Copy index if apache2 is installed
      ansible.builtin.template:
        src: ../files/index.html.j2
        dest: /var/www/html/index.html
        mode: '0644'
      notify: Restart apache
      when: "'apache2' in ansible_facts.packages"
  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: apache2
        state: restarted

- name: Install nginx
  hosts: nginx
  remote_user: root
  become: true
  become_user: root

  tasks:
    - name: Install package nginx
      ansible.builtin.apt:
        update_cache: true
        name: "{{ item }}"
        state: present
      loop:
        - git
        - nginx
        - cowsay

    - name: Gather the rpm package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Install ufw
      ansible.builtin.apt:
        update_cache: true
        name: ufw
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Copy index.html if nginx is installed
      ansible.builtin.template:
        src: ../files/index.html.j2
        dest: /var/www/html/index.html
        mode: '0644'
      notify: Restart nginx
      when: "'nginx' in ansible_facts.packages"

    - name: Copy day if nginx is installed
      ansible.builtin.template:
        src: ../files/day.j2
        dest: /etc/jour
        mode: '0644'

    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
      when: "'nginx' in ansible_facts.packages"
      
  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
