---
- name: Converge
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false

    - name: Install unzip
      ansible.builtin.apt:
        name: unzip
        state: present

  roles:
    - tp8.wordpress
