---
- name: Set personal SSH key
  hosts: all
  gather_facts: false
  become: true

  # Vagrant provison runs this file, so you don't actually need an inventory
  # it does that for you.
  # Basically we setup a bunch of environment stuff so we can ssh into the host
  # Using all the data from all.yml

  tasks:
    - name: Set authorized key took from file
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', '/home/' + lookup('env', 'USER') + '/.ssh/id_rsa.pub') }}"
