---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt: 
        update_cache: yes
        cache_valid_time: 600
      changed_when: false

    - name: Install unzip
      ansible.builtin.apt:
        name: unzip
        state: present
        
  roles:
    - tp8.wordpress
