---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: wordpress-ubuntu2404
    image: "geerlingguy/docker-ubuntu2404-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    published_ports:
      - 80/tcp

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible-${USER}/tmp/

verifier:
  name: ansible
