---
role_name: 1
dependency:
    name: galaxy
    options:
      ignore-errors: true
driver:
  name: docker
platforms:
  - name: ubuntu24
    image: "geerlingguy/docker-ubuntu2404-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
    name: ansible
    playbooks:
        converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    # image: quay.io/centos/centos:stream8
