---
- name: Install vim et vérifier /etc/passwd
  hosts: all
  remote_user: root
  become: true
  become_user: root

  tasks:
    - name: Install vim
      ansible.builtin.apt:
        name: vim
        state: present

    - name: Vérifier l'existance de /etc/passwd
      ansible.builtin.apt:
        path: /etc/passwd


