---
# tasks file for tp8.wordpress
- name: Install apache, php, mysql-server & other dependencies
  ansible.builtin.apt:
    name:
      - apache2
      - ghostscript
      - libapache2-mod-php
      - mysql-server
      - php
      - php-bcmath
      - php-curl
      - php-imagick
      - php-intl
      - php-json
      - php-mbstring
      - php-mysql
      - php-xml
      - php-zip
      - python3-pymysql
    state: present
    update_cache: true

- name: Enable Apache2 modules
  community.general.apache2_module:
    state: present
    name: rewrite

- name: Create wordpress directory
  ansible.builtin.file:
    path: /var/www/wordpress/
    state: directory
    recurse: true

- name: Download and unarchive wordpress
  ansible.builtin.unarchive:
    src: https://fr.wordpress.org/latest-fr_FR.zip
    dest: /var/www
    remote_src: true

- name: Configure apache vhost for wordpress
  ansible.builtin.template:
    src: vhost.j2
    dest: /etc/apache2/sites-available/000-default.conf
    mode: '0644'
  notify: Restart apache2

- name: Configure wordpress wp-config.php
  ansible.builtin.template:
    src: wp-config.j2
    dest: /var/www/wordpress/wp-config.php
    mode: '0644'

- name: Start mysql
  ansible.builtin.service:
    name: mysql
    state: started

- name: DB set root user password
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    login_unix_socket: "/run/mysqld/mysqld.sock"
    name: root
    password: "{{ mariadb_root_password }}"
    host_all: true
    state: present

- name: Create wordpress database
  community.mysql.mysql_db:
    name: "{{ wordpress_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    login_unix_socket: "/run/mysqld/mysqld.sock"

- name: Create database user
  community.mysql.mysql_user:
    name: "{{ wordpress_db_username }}"
    password: "{{ wordpress_db_password }}"
    priv: '*.*:ALL'
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    login_unix_socket: "/run/mysqld/mysqld.sock"
