---
- name: Installer et configurer node[1-3]
  hosts: all
  remote_user: root
  become: true
  become_user: root

  tasks:
    - name: Install apache and mysql-server
      ansible.builtin.apt:
        update_cache: true
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - mysql-server
      when: "'apache' in group_names"

    - name: Install git nginx and cowsay
      ansible.builtin.apt:
        update_cache: true
        name: "{{ item }}"
        state: present
      loop:
        - git
        - nginx
        - cowsay
      when: "'nginx' in group_names"

    - name: Install ufw on ubuntu
      ansible.builtin.apt:
        name: ufw
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Gather the rpm package facts
      ansible.builtin.package_facts:
        manager: auto
      tags: apache

    - name: Copy index.html if apache2 or nginx is installed
      ansible.builtin.template:
        src: index.html.j2
        dest: /var/www/html/index.html
        mode: '0644'
      when: "'apache2' in ansible_facts.packages or 'nginx' in ansible_facts.packages"
      tags: apache

    - name: Start apache2
      ansible.builtin.service:
        name: apache2
        state: started
      when: "'apache2' in ansible_facts.packages"

    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started
      when: "'nginx' in ansible_facts.packages"

    - name: Copy day
      ansible.builtin.template:
        src: day.j2
        dest: /etc/jour
        mode: '0644'
