---
- name: Uninstall package
  hosts: all
  remote_user: root
  become: true
  become_user: root

  tasks:
    - name: Install package
      ansible.builtin.apt:
        update_cache: true
        name: "{{ item }}"
        state: absent
      loop:
        - apache2
        - mysql-server
        - nginx
        - cowsay
