---
- name: Install mySql
  hosts: web
  remote_user: root
  become: true
  become_user: root

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.apache

  handlers:
    - name: Restart Apache
      ansible.builtin.service:
        name: apache2
        state: restarted

  tasks:
    - name: Dependencies Install
      ansible.builtin.apt:
        update_cache: true
        name:
          - ghostscript 
          - libapache2-mod-php
          - php
          - php-bcmath
          - php-curl
          - php-imagick
          - php-intl
          - php-json
          - php-mbstring
          - php-mysql
          - php-xml
          - php-zip
        state: present

    - name: Recursively create directory
      ansible.builtin.file:
        path: "/var/www/"
        state: directory
        recurse: yes
        owner: root
        group: root
    
    - name: Download wordpress
      ansible.builtin.get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress-latest.tar.gz
        mode: '0440'

    - name: Extract wordpress-latest.tar.gz into "/var/www/"
      ansible.builtin.unarchive:
        src: /tmp/wordpress-latest.tar.gz
        dest: "/var/www/"
        remote_src: yes
      notify: ["Restart Apache"] 

    - name: Copy wp-config.php
      ansible.builtin.template:
        src: wp-config.php.j2
        dest: "{{ apache_vhosts[0].documentroot }}/wp-config.php"
        mode: '0644'
