---
- name: Install mySql
  hosts: web
  remote_user: root
  become: true
  become_user: root

  roles:
    - geerlingguy.apache

  tasks:
    - name: Dependencies Install
      ansible.builtin.apt:
        update_cache: true
        name:
          - ghostscript 
          - libapache2-mod-php
          - php
          - php-bcmath
          - php-curl
          - php-imagick
          - php-intl
          - php-json
          - php-mbstring
          - php-mysql
          - php-xml
          - php-zip
        state: present

    - name: Recursively create directory
      ansible.builtin.file:
        path: "{{apache_vhosts.documentroot}}"
        state: directory
        recurse: yes
        owner: root
        group: root
    
    - name: Download wordpress
      ansible.builtin.get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress-latest.tar.gz
        mode: '0440'

    - name: Extract wordpress-latest.tar.gz into "{{apache_vhosts.documentroot}}"
      ansible.builtin.unarchive:
        src: /tmp/wordpress-latest.tar.gz
        dest: "{{apache_vhosts.documentroot}}"
        notify: Reload Apache
